import { Flower, Occasion } from './types';

export const FLOWERS: Flower[] = [
  {
    code: 'rose-red',
    name: 'Red Rose',
    emoji: '🌹',
    color: '#f43f5e',
    meaning: 'Deep love and passion – the classic declaration of the heart.',
    bestForOccasions: ['love', 'birthday', 'general'],
  },
  {
    code: 'rose-pink',
    name: 'Pink Rose',
    emoji: '🌸',
    color: '#ec4899',
    meaning: 'Admiration, grace, and gentle affection.',
    bestForOccasions: ['love', 'birthday', 'gratitude', 'friendship'],
  },
  {
    code: 'rose-white',
    name: 'White Rose',
    emoji: '🤍',
    color: '#f1f5f9',
    meaning: 'Purity, new beginnings, and sincere sympathy.',
    bestForOccasions: ['sympathy', 'apology', 'general'],
  },
  {
    code: 'sunflower',
    name: 'Sunflower',
    emoji: '🌻',
    color: '#facc15',
    meaning: 'Happiness, loyalty, and a spirit that always seeks the sun.',
    bestForOccasions: ['birthday', 'congratulations', 'friendship', 'general'],
  },
  {
    code: 'tulip-pink',
    name: 'Pink Tulip',
    emoji: '🌷',
    color: '#f9a8d4',
    meaning: 'Caring thoughts and warm wishes sent your way.',
    bestForOccasions: ['birthday', 'love', 'gratitude'],
  },
  {
    code: 'tulip-yellow',
    name: 'Yellow Tulip',
    emoji: '🌼',
    color: '#fde68a',
    meaning: 'Cheerfulness and a sunshine-bright friendship.',
    bestForOccasions: ['friendship', 'birthday', 'congratulations'],
  },
  {
    code: 'lavender',
    name: 'Lavender',
    emoji: '💜',
    color: '#c4b5fd',
    meaning: 'Calm, devotion, and a quiet, enduring love.',
    bestForOccasions: ['love', 'sympathy', 'gratitude', 'general'],
  },
  {
    code: 'daisy',
    name: 'Daisy',
    emoji: '🌼',
    color: '#fef9c3',
    meaning: 'Innocence, new beginnings, and a cheerful spirit.',
    bestForOccasions: ['birthday', 'friendship', 'general', 'apology'],
  },
  {
    code: 'lily-white',
    name: 'White Lily',
    emoji: '🌺',
    color: '#f0fdf4',
    meaning: 'Renewed hope, peace, and heartfelt condolences.',
    bestForOccasions: ['sympathy', 'apology', 'general'],
  },
  {
    code: 'lily-orange',
    name: 'Orange Lily',
    emoji: '🧡',
    color: '#fb923c',
    meaning: 'Pride, confidence, and warm congratulations.',
    bestForOccasions: ['congratulations', 'birthday', 'general'],
  },
  {
    code: 'orchid',
    name: 'Purple Orchid',
    emoji: '🌸',
    color: '#a855f7',
    meaning: 'Rare beauty, strength, and luxury.',
    bestForOccasions: ['love', 'birthday', 'congratulations'],
  },
  {
    code: 'peony',
    name: 'Peony',
    emoji: '🌸',
    color: '#fda4af',
    meaning: 'Romance, prosperity, and a life full of good fortune.',
    bestForOccasions: ['love', 'birthday', 'congratulations'],
  },
  {
    code: 'hydrangea',
    name: 'Hydrangea',
    emoji: '💙',
    color: '#bfdbfe',
    meaning: 'Heartfelt emotions, gratitude, and understanding.',
    bestForOccasions: ['gratitude', 'sympathy', 'apology', 'friendship'],
  },
  {
    code: 'chrysanthemum',
    name: 'Chrysanthemum',
    emoji: '🌼',
    color: '#fed7aa',
    meaning: 'Joy, longevity, and optimism for the journey ahead.',
    bestForOccasions: ['birthday', 'congratulations', 'sympathy'],
  },
  {
    code: 'forget-me-not',
    name: 'Forget-Me-Not',
    emoji: '💙',
    color: '#93c5fd',
    meaning: 'True love and rememberance – always in your thoughts.',
    bestForOccasions: ['love', 'sympathy', 'friendship'],
  },
  {
    code: 'violet',
    name: 'Violet',
    emoji: '🌷',
    color: '#7c3aed',
    meaning: 'Faithfulness, modesty, and steadfast friendship.',
    bestForOccasions: ['friendship', 'love', 'gratitude'],
  },
  {
    code: 'marigold',
    name: 'Marigold',
    emoji: '🌾',
    color: '#f97316',
    meaning: 'Warmth, creativity, and glowing admiration.',
    bestForOccasions: ['birthday', 'congratulations', 'gratitude'],
  },
  {
    code: 'carnation-pink',
    name: 'Pink Carnation',
    emoji: '💗',
    color: '#f472b6',
    meaning: 'A mother\'s love, gratitude, and pure affection.',
    bestForOccasions: ['love', 'gratitude', 'birthday'],
  },
  {
    code: 'iris',
    name: 'Purple Iris',
    emoji: '🌸',
    color: '#818cf8',
    meaning: 'Wisdom, hope, and the courage to move forward.',
    bestForOccasions: ['sympathy', 'congratulations', 'general'],
  },
  {
    code: 'magnolia',
    name: 'Magnolia',
    emoji: '🤍',
    color: '#fef3c7',
    meaning: 'Dignity, nobility, and a love of nature.',
    bestForOccasions: ['sympathy', 'love', 'general'],
  },
  {
    code: 'cherry-blossom',
    name: 'Cherry Blossom',
    emoji: '🌸',
    color: '#fbcfe8',
    meaning: 'The beauty of fleeting moments and renewal of life.',
    bestForOccasions: ['birthday', 'apology', 'general'],
  },
  {
    code: 'zinnia',
    name: 'Zinnia',
    emoji: '🌺',
    color: '#ef4444',
    meaning: 'Lasting friendship, daily remembrance, and goodness.',
    bestForOccasions: ['friendship', 'gratitude', 'birthday'],
  },
];

export function getFlowersByOccasion(occasion: Occasion): Flower[] {
  if (occasion === 'general') return FLOWERS;
  return FLOWERS.filter((f) => f.bestForOccasions.includes(occasion));
}

export function getFlowerByCode(code: string): Flower | undefined {
  return FLOWERS.find((f) => f.code === code);
}
